# AT generally uses node 4.8.0 and so this will too
stages:
    - lint
    - test
    - publish

lint:
    image: $DOCKER_URL/node:latest
    stage: lint
    script:
        - npm ci
        - npm run lint

node:4:
    image: $DOCKER_URL/node:4.8.0
    stage: test
    script:
        - npm install --global npm@5.10.0
        - npm install
        - npm install mocha@5.2.0
        - npm test

node:6:
    image: $DOCKER_URL/node:6
    stage: test
    script:
        - npm install
        - npm install mocha@6.2.2
        - npm test

node:8:
  image: $DOCKER_URL/node:8.11.1
  stage: test
  script:
    - npm install --global npm@5.10.0
    - npm ci
    - npm install mocha@7
    - npm run test

node:latest:
    image: $DOCKER_URL/node:latest
    stage: test
    script:
        - npm ci
        - npm test

coverage:
    image: $DOCKER_URL/node:latest
    stage: test
    script:
        - npm ci
        - npm run coverage
    artifacts:
        paths:
            - coverage

pages:
  stage: publish
  image: $DOCKER_URL/node:latest
  dependencies:
    - coverage
  script:
    - COVERAGE_DOCS=./public/coverage-docs
    - mkdir -p ${COVERAGE_DOCS}
    - cp -R coverage/* ${COVERAGE_DOCS}
  artifacts:
    paths:
      - public
  only:
    - develop
